apiVersion: apps/v1
kind: Deployment
metadata:
  name: deposit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deposit
  template:
    metadata:
      labels:
        app: deposit
    spec:
      containers:
      - name: deposit
        image: aryansahuuu/bankform:v1  # Updated image path
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017"
      imagePullSecrets:
      - name: my-registry-secret  # Only needed if using a private registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: deposit-service
spec:
  selector:
    app: deposit
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
