apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: deposits
        image: aryansahuuu/bankform:v1
        ports:
        - containerPort: 3011
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/restaurant"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017