apiVersion: v1
kind: Service
metadata:
  name: deposit-service
spec:
  selector:
    app: deposit
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer  # Change to 'ClusterIP' if you don't need external access
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP  # Exposes the service only within the cluster
